nfl_app/nfl/urls.py
from django.urls import path
from . import views

app_name = 'nfl' 

urlpatterns = [
    path('duenio/create/', views.CreateDuenio.as_view(), name='create_duenio'),
    path('duenio/list/', views.ListDuenios.as_view(), name='list_duenio'),
    path('duenio/<int:pk>/', views.DetailDuenio.as_view(), name='detail_duenio'),
    path('duenio/<int:pk>/update/', views.UpdateDuenio.as_view(), name='update_duenio'),
    path('duenio/<int:pk>/delete/', views.DeleteDuenio.as_view(), name='delete_duenio'),

    # URLs para Ciudad
    path('ciudad/create/', views.CreateCiudad.as_view(), name='create_ciudad'),
    path('ciudad/list/', views.ListCiudades.as_view(), name='list_ciudades'),
    path('ciudad/<int:pk>/', views.DetailCiudad.as_view(), name='detail_ciudad'),
    path('ciudad/update/<int:pk>/', views.UpdateCiudad.as_view(), name='update_ciudad'),
    path('ciudad/<int:pk>/delete/', views.DeleteCiudad.as_view(), name='delete_ciudad'),

    # URLs para Equipo
    path('equipo/create/', views.CreateEquipo.as_view(), name='create_equipo'),
    path('equipo/list/', views.ListEquipos.as_view(), name='list_equipo'),
    path('equipo/<int:pk>/', views.DetailEquipo.as_view(), name='detail_equipo'),
    path('equipo/<int:pk>/update/', views.UpdateEquipo.as_view(), name='update_equipo'),
    path('equipo/<int:pk>/delete/', views.DeleteEquipo.as_view(), name='delete_equipo'),

    # URLs para Estadio
    path('estadio/create/', views.CreateEstadio.as_view(), name='create_estadio'),
    path('estadio/list/', views.ListEstadios.as_view(), name='list_estadio'),
    path('estadio/<int:pk>/', views.DetailEstadio.as_view(), name='detail_estadio'),
    path('estadio/<int:pk>/update/', views.UpdateEstadio.as_view(), name='update_estadio'),
    path('estadio/<int:pk>/delete/', views.DeleteEstadio.as_view(), name='delete_estadio'),

    # URLs para Jugador
    path('jugador/create/', views.CreateJugador.as_view(), name='create_jugador'),
    path('jugador/list/', views.ListJugadores.as_view(), name='list_jugador'),
    path('jugador/<int:pk>/', views.DetailJugador.as_view(), name='detail_jugador'),
    path('jugador/<int:pk>/update/', views.UpdateJugador.as_view(), name='update_jugador'),
    path('jugador/<int:pk>/delete/', views.DeleteJugador.as_view(), name='delete_jugador'),
# URLs para Partido
    path('partido/create/', views.CreatePartido.as_view(), name='create_partido'),
    path('partido/list/', views.ListPartidos.as_view(), name='list_partido'),
    path('partido/<int:pk>/', views.DetailPartido.as_view(), name='detail_partido'),
    path('partido/<int:pk>/update/', views.UpdatePartido.as_view(), name='update_partido'),
    path('partido/<int:pk>/delete/', views.DeletePartido.as_view(), name='delete_partido'),

    path('boleto/create/', views.CreateBoleto.as_view(), name='create_boleto'),
    path('boleto/list/', views.ListBoletos.as_view(), name='list_boletos'),
    path('boleto/<int:pk>/', views.DetailBoleto.as_view(), name='detail_boleto'),
    path('boleto/<int:pk>/update/', views.UpdateBoleto.as_view(), name='update_boleto'),
    path('boleto/<int:pk>/delete/', views.DeleteBoleto.as_view(), name='delete_boleto'),

    path('liga/create/', views.CreateLiga.as_view(), name='create_liga'),
    path('liga/list/', views.ListLigas.as_view(), name='list_liga'),
    path('liga/<int:pk>/', views.DetailLiga.as_view(), name='detail_liga'),
    path('liga/<int:pk>/update/', views.UpdateLiga.as_view(), name='update_liga'),
    path('liga/<int:pk>/delete/', views.DeleteLiga.as_view(), name='delete_liga'),

    # ... Otras URLs existentes ...
]

nfl_app/nfl_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('nfl/', include('nfl.urls')),
]

nfl_app/nfl/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta

# Create your models here.
from django.db import models

class Duenio(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)  # Agregamos el campo apellido

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class Ciudad(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    

    def __str__(self):
        return self.nombre

class Liga(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.nombre

class Estadio(models.Model):
    id = models.AutoField(primary_key=True)
    capacidad = models.IntegerField()
    nombre = models.CharField(max_length=100)
    duenio = models.ForeignKey(Duenio, on_delete=models.CASCADE)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre
    
class Equipo(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    liga = models.ForeignKey(Liga, on_delete=models.CASCADE)
    duenio = models.ForeignKey(Duenio, on_delete=models.CASCADE)
    estadio = models.ForeignKey(Estadio, on_delete=models.CASCADE)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre


    
class Jugador(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)  # Nuevo campo
    alias = models.CharField(max_length=50)      # Nuevo campo
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nombre} {self.apellido})"
    
class Partido(models.Model):
    id = models.AutoField(primary_key=True)
    equipo_local = models.ForeignKey(Equipo, on_delete=models.CASCADE, related_name='partidos_local')
    equipo_visitante = models.ForeignKey(Equipo, on_delete=models.CASCADE, related_name='partidos_visitante')
    estadio = models.ForeignKey(Estadio, on_delete=models.CASCADE)
    fecha = models.DateTimeField()
    # Otros campos que desees agregar

    def __str__(self):
        return f"{self.equipo_local.nombre} vs {self.equipo_visitante.nombre} ({self.estadio.nombre})"

class Boleto(models.Model):
    id = models.AutoField(primary_key=True)
    partido = models.ForeignKey(Partido, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)  # Nuevo campo para la cantidad de boletos
    # Otros campos relacionados con el boleto que desees agregar

    def __str__(self):
        return f"{self.cantidad} boleto(s) para {self.partido}"



 
 

nfl_app/nfl/forms.py
from django import forms
from .models import Ciudad, Equipo, Estadio, Duenio, Jugador, Partido, Boleto, Liga

class CiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = ["nombre"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre de la ciudad"}),
        }

class LigaForm(forms.ModelForm):
    class Meta:
        model = Liga
        fields = ["nombre", "ciudad"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre de la liga"}),
            "ciudad": forms.Select(attrs={"class": "form-control"}),
        }

class EquipoForm(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = ["nombre", "ciudad", "duenio", "estadio", "liga"]  # Agregar "duenio" al formulario
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del equipo"}),
            "ciudad": forms.Select(attrs={"class": "form-control"}),
            "liga": forms.Select(attrs={"class": "form-control"}),
            "estadio": forms.Select(attrs={"class": "form-control"}),
            "duenio": forms.Select(attrs={"class": "form-control"}),  # Agregar widget para Duenio
        }

class EstadioForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = ["nombre", "duenio", "ciudad", "capacidad"]  # Agregar "duenio" al formulario
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del estadio"}),
            "capacidad": forms.NumberInput(attrs={"class": "form-control", "placeholder": "Nombre del estadio"}),
            "duenio": forms.Select(attrs={"class": "form-control"}),  # Agregar widget para Duenio
            "ciudad": forms.Select(attrs={"class": "form-control"}),
        }

class JugadorForm(forms.ModelForm):
    class Meta:
        model = Jugador
        fields = ["nombre", "apellido", "alias", "equipo"]  # Agregar "apellido" y "alias" al formulario
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del jugador"}),
            "apellido": forms.TextInput(attrs={"class": "form-control", "placeholder": "Apellido del jugador"}),  # Nuevo campo
            "alias": forms.TextInput(attrs={"class": "form-control", "placeholder": "Alias del jugador"}),      # Nuevo campo
            "equipo": forms.Select(attrs={"class": "form-control"}),
        }


class DuenioForm(forms.ModelForm):
    class Meta:
        model = Duenio
        fields = ["nombre", "apellido"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del dueño"}),
            "apellido": forms.TextInput(attrs={"class": "form-control", "placeholder": "Apellido del dueño"}),
        }

class PartidoForm(forms.ModelForm):
    class Meta:
        model = Partido
        fields = ["equipo_local", "equipo_visitante", "estadio", "fecha"]
        widgets = {
            "equipo_local": forms.Select(attrs={"class": "form-control"}),
            "equipo_visitante": forms.Select(attrs={"class": "form-control"}),
            "estadio": forms.Select(attrs={"class": "form-control"}),
            "fecha": forms.SelectDateWidget()
            # Agrega widgets adicionales según tus necesidades
        }

class BoletoForm(forms.ModelForm):
    class Meta:
        model = Boleto
        fields = ['partido', 'cantidad']  # Agregar otros campos según sea necesario
        widgets = {
            'partido': forms.Select(attrs={'class': 'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control'}),
            # Agregar widgets para otros campos según sea necesario
        }

nfl_app/nfl/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from .forms import CiudadForm, EquipoForm, EstadioForm, DuenioForm, JugadorForm, PartidoForm, BoletoForm, LigaForm
from .models import Ciudad, Equipo, Estadio, Duenio, Jugador, Partido, Boleto, Liga
# Vistas para Ciudad
class CreateCiudad(CreateView):
    template_name = "nfl/create_ciudad.html"
    model = Ciudad
    form_class = CiudadForm
    success_url = reverse_lazy('nfl:list_ciudades')

class ListCiudades(ListView):
    template_name = "nfl/list_ciudades.html"  
    model = Ciudad
    context_object_name = 'ciudades'

class DetailCiudad(DetailView):
    template_name = "nfl/detail_ciudad.html"
    model = Ciudad
    context_object_name = 'ciudad'

class UpdateCiudad(UpdateView):
    template_name = "nfl/update_ciudad.html"
    model = Ciudad
    form_class = CiudadForm
    success_url = reverse_lazy('nfl:list_ciudades')

class DeleteCiudad(DeleteView):
    template_name = "nfl/delete_ciudad.html"
    model = Ciudad
    success_url = reverse_lazy('nfl:list_ciudades')

# Vistas para Equipo
class CreateEquipo(CreateView):
    template_name = "nfl/create_equipo.html"
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy('nfl:list_equipo')

class ListEquipos(ListView):
    template_name = "nfl/list_equipo.html"
    model = Equipo
    context_object_name = 'equipos'

class DetailEquipo(DetailView):
    template_name = "nfl/detail_equipo.html"
    model = Equipo
    context_object_name = 'equipo'

class UpdateEquipo(UpdateView):
    template_name = "nfl/update_equipo.html"
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy('nfl:list_equipo')

class DeleteEquipo(DeleteView):
    template_name = "nfl/delete_equipo.html"
    model = Equipo
    success_url = reverse_lazy('nfl:list_equipo')


# Vistas para Estadio
class CreateEstadio(CreateView):
    template_name = "nfl/create_estadio.html"
    model = Estadio
    form_class = EstadioForm
    success_url = reverse_lazy('nfl:list_estadio')

class ListEstadios(ListView):
    template_name = "nfl/list_estadio.html"  
    model = Estadio
    context_object_name = 'estadios'

class DetailEstadio(DetailView):
    template_name = "nfl/detail_estadio.html"
    model = Estadio
    context_object_name = 'estadio'

class UpdateEstadio(UpdateView):
    template_name = "nfl/update_estadio.html"
    model = Estadio
    form_class = EstadioForm
    success_url = reverse_lazy('nfl:list_estadio')

class DeleteEstadio(DeleteView):
    template_name = "nfl/delete_estadio.html"
    model = Estadio
    success_url = reverse_lazy('nfl:list_estadio')

# Vistas para Duenio
class CreateDuenio(CreateView):
    template_name = "nfl/create_duenio.html"
    model = Duenio
    form_class = DuenioForm
    success_url = reverse_lazy('nfl:list_duenio')

class ListDuenios(ListView):
    template_name = "nfl/list_duenio.html"
    model = Duenio
    context_object_name = 'duenios'

class DetailDuenio(DetailView):
    template_name = "nfl/detail_duenio.html"
    model = Duenio
    context_object_name = 'duenio'

class UpdateDuenio(UpdateView):
    template_name = "nfl/update_duenio.html"
    model = Duenio
    form_class = DuenioForm
    success_url = reverse_lazy('nfl:list_duenio')

class DeleteDuenio(DeleteView):
    template_name = "nfl/delete_duenio.html"
    model = Duenio
    success_url = reverse_lazy('nfl:list_duenio')


# Vistas para Jugador
class CreateJugador(CreateView):
    template_name = "nfl/create_jugador.html"
    model = Jugador
    form_class = JugadorForm
    success_url = reverse_lazy('nfl:list_jugador')

class ListJugadores(ListView):
    template_name = "nfl/list_jugador.html"
    model = Jugador
    context_object_name = 'jugadores'

class DetailJugador(DetailView):
    template_name = "nfl/detail_jugador.html"
    model = Jugador
    context_object_name = 'jugador'

class UpdateJugador(UpdateView):
    template_name = "nfl/update_jugador.html"
    model = Jugador
    form_class = JugadorForm
    success_url = reverse_lazy('nfl:list_jugador')

class DeleteJugador(DeleteView):
    template_name = "nfl/delete_jugador.html"
    model = Jugador
    success_url = reverse_lazy('nfl:list_jugador')


class CreatePartido(CreateView):
    template_name = "nfl/create_partido.html"
    model = Partido
    form_class = PartidoForm
    success_url = reverse_lazy('nfl:list_partido')

class ListPartidos(ListView):
    template_name = "nfl/list_partido.html"
    model = Partido
    context_object_name = 'partidos'

class DetailPartido(DetailView):
    template_name = "nfl/detail_partido.html"
    model = Partido
    context_object_name = 'partido'

class UpdatePartido(UpdateView):
    template_name = "nfl/update_partido.html"
    model = Partido
    form_class = PartidoForm
    success_url = reverse_lazy('nfl:list_partido')

class DeletePartido(DeleteView):
    template_name = "nfl/delete_partido.html"
    model = Partido
    success_url = reverse_lazy('nfl:list_partido')

class CreateBoleto(CreateView):
    template_name = "nfl/create_boleto.html"
    model = Boleto
    form_class = BoletoForm
    success_url = reverse_lazy('nfl:list_boletos')

class ListBoletos(ListView):
    template_name = "nfl/list_boleto.html"
    model = Boleto
    context_object_name = 'boletos'

class DetailBoleto(DetailView):
    template_name = "nfl/detail_boleto.html"
    model = Boleto
    context_object_name = 'boleto'

class UpdateBoleto(UpdateView):
    template_name = "nfl/update_boleto.html"
    model = Boleto
    form_class = BoletoForm
    success_url = reverse_lazy('nfl:list_boletos')

class DeleteBoleto(DeleteView):
    template_name = "nfl/delete_boleto.html"
    model = Boleto
    success_url = reverse_lazy('nfl:list_boletos')

class CreateLiga(CreateView):
    template_name = "nfl/create_liga.html"
    model = Liga
    form_class = LigaForm
    success_url = reverse_lazy('nfl:list_liga')

class ListLigas(ListView):
    template_name = "nfl/list_liga.html"
    model = Liga
    context_object_name = 'ligas'

class DetailLiga(DetailView):
    template_name = "nfl/detail_liga.html"
    model = Liga
    context_object_name = 'liga'

class UpdateLiga(UpdateView):
    template_name = "nfl/update_liga.html"
    model = Liga
    form_class = LigaForm
    success_url = reverse_lazy('nfl:list_liga')

class DeleteLiga(DeleteView):
    template_name = "nfl/delete_liga.html"
    model = Liga
    success_url = reverse_lazy('nfl:list_liga')

nfl_app/nfl/templates/nfl/create_estadio.html
{% extends "base/base.html" %}

{% block title %}
  Crear Estadio
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'nfl:list_estadio' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

nfl_app/nfl/templates/nfl/delete_boleto.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Boleto
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar este boleto?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'nfl:list_boletos' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

nfl_app/nfl/templates/nfl/delete_equipo.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Equipo
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar el Equipo '{{ equipo.nombre }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'nfl:list_equipo' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

nfl_app/nfl/templates/nfl/delete_liga.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Liga
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar la liga '{{ liga.nombre }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'nfl:list_liga' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

nfl_app/nfl/templates/nfl/delete_partido.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Partido
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar el partido entre '{{ partido.equipo_local.nombre }}' y '{{ partido.equipo_visitante.nombre }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'nfl:list_partido' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

nfl_app/nfl/templates/nfl/detail_duenio.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del Duenio
{% endblock title %}

{% block content %}
  <h2>{{ duenio.nombre }}</h2>
  <p>Este es el Duenio {{ duenio.nombre }}.</p>
  <a href="{% url 'nfl:list_duenio' %}" class="btn btn-secondary">Volver a la lista de Dueños</a>
{% endblock content %}

nfl_app/nfl/templates/nfl/detail_estadio.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del Estadio
{% endblock title %}

{% block content %}
  <h2>{{ estadio.nombre }}</h2>
  <p>Este es el Estadio '{{ estadio.nombre }}' que pertenece a '{{ estadio.duenio.nombre }}' y se encuentra en '{{ estadio.ciudad.nombre }}'.</p>
  <a href="{% url 'nfl:list_estadio' %}" class="btn btn-secondary">Volver a la lista de Estadios</a>
{% endblock content %}

nfl_app/nfl/templates/nfl/list_equipo.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Equipos
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Ciudad</th>
      <th>Dueño</th>      {# Nueva columna #}
      <th>Estadio</th>    {# Nueva columna #}
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'nfl:create_equipo' %}" class="btn btn-success">Crear Equipo</a>
      {% for equipo in equipos %}
        <tr>
          <td>{{ equipo.id }}</td>
          <td>{{ equipo.nombre }}</td>
          <td>{{ equipo.ciudad.nombre }}</td>
          <td>{{ equipo.duenio.nombre }}</td>    {# Nueva columna #}
          <td>{{ equipo.estadio.nombre }}</td>   {# Nueva columna #}
          <td>{{ equipo.liga.nombre }}</td>
          <td>
            <a href="{% url 'nfl:detail_equipo' equipo.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'nfl:update_equipo' equipo.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'nfl:delete_equipo' equipo.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

nfl_app/nfl/templates/nfl/list_estadio.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Estadios
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Capacidad</th>  {# Nueva columna #}
      <th>Dueño</th>      {# Nueva columna #}
      <th>Ciudad</th>     {# Nueva columna #}
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'nfl:create_estadio' %}" class="btn btn-success">Crear Estadio</a>
      {% for estadio in estadios %}
        <tr>
          <td>{{ estadio.id }}</td>
          <td>{{ estadio.nombre }}</td>
          <td>{{ estadio.capacidad }}</td>            {# Nueva columna #}
          <td>{{ estadio.duenio.nombre }}</td>       {# Nueva columna #}
          <td>{{ estadio.ciudad.nombre }}</td>       {# Nueva columna #}
          <td>
            <a href="{% url 'nfl:detail_estadio' estadio.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'nfl:update_estadio' estadio.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'nfl:delete_estadio' estadio.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

nfl_app/nfl/templates/nfl/update_boleto.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Boleto
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'nfl:list_boleto' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

nfl_app/nfl/templates/nfl/update_equipo.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Equipo
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'nfl:list_equipo' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

nfl_app/nfl/templates/nfl/update_estadio.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Estadio
{% endblock title %}

{% block content %}
  <form action="" method="post" class "form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'nfl:list_estadio' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

nfl_app/nfl/templates/nfl/update_jugador.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Jugador
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'nfl:list_jugador' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

nfl_app/nfl/templates/nfl/update_liga.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Liga
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'nfl:list_liga' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}